spring:
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 600000
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
